In [1]:
import numpy as np

In [13]:
w1=5
b1=2
x=3

In [17]:
output=x*w1+b1

In [40]:
output

17

In [76]:
import math

def sigmoid(val):
    return 1/(1+np.exp(-x))
    

In [78]:
 sigmoid(x)

0.9525741268224334

In [80]:
prediction=sigmoid(output)

In [82]:
prediction

0.9525741268224334

In [188]:
w=np.array(([5 ,-2],[9, 73]) )
w1=np.array(([4],[12] ))
w2=np.array(([3],[10]))
x=np.array(([3,2]))
b1=2
b2=-3
b3=4
out=np.dot(x,w)+b1
out

array([ 35, 142])

In [180]:

prid=sigmoid(out)
prid
    

array([0.95257413, 0.88079708])

In [190]:
out2=np.dot(out,w1)+b2
out2 

array([1841])

In [194]:
out3=np.dot(out2,w2)+b3

ValueError: shapes (1,) and (2,1) not aligned: 1 (dim 0) != 2 (dim 0)