In [1]:
import numpy as np

In [23]:
W = np.array(([5, -2], [9, 73]), dtype=float)
W2 = np.array(([4], [12]), dtype=float)
b1 = 2
b2 = -3

In [20]:
x = np.array(([3, 2]), dtype=float)

In [29]:
output1 = np.dot(x, W) + b1
output1

array([ 35., 142.])

In [13]:
def sigmoid(val):
    return 1/(1+np.exp(-val))

In [15]:
sigmoid(x)

0.9525741268224334

In [28]:
prediction = sigmoid(output1)
prediction

array([1., 1.])

In [17]:
prediction = prediction * 100

In [18]:
prediction

99.99999586006244

In [30]:
output_2 = np.dot(output1, W2) + b2

In [31]:
output_2

array([1841.])